### ISSUE TITLE
Would you accept a pull request to add timezone to $fields?

### ISSUE THREAD

**Issue by BrendanTWhite** [adamwathan/socialnorm-facebook#1]
Hi Adam, as discussed on [my other post](https://github.com/adamwathan/eloquent-oauth-l5/issues/13), I'd love to get the timezone for the logged in user from Facebook. (Others might find this useful as well.)

Currently it's not appearing in the `$details` when I use [eloquent-oauth-l5](https://github.com/adamwathan/eloquent-oauth-l5) (or in `$details->raw`). But it will appear in `$details->raw` if we add 'timezone' to the `$fields` array in lines 14-17 of [FacebookProvider.php](https://github.com/adamwathan/socialnorm-facebook/blob/master/src/FacebookProvider.php#L14-L17).

I understand that not all providers will give the timezone, but if it's only in the `$details->raw`, would that be OK? And if I were to add 'timezone' (and possibly one or two other fields from the Facebook [public profile](https://developers.facebook.com/docs/facebook-login/permissions/v2.4#reference-public_profile)) to `$fields` and submit a pull request, do you think you'd want to accept it?

Regards,
       Brendan.

**Comment by adamwathan** [comment]
Hey Brendan! Would totally accept it, feel free to submit :)

**Comment by BrendanTWhite** [comment]
Cool, thanks. I will have a go at this some time in the next few days.  :-)

**Comment by BrendanTWhite** [comment]
In case anyone's ever looking at this, I've put together a [pull request](https://github.com/adamwathan/socialnorm-facebook/pull/2).
